### ISSUE TITLE
Error on doing file Checkup

### ISSUE THREAD

**Issue by grigzy28** [lukechampine/user#5]
```
root@sia-test:~# user checkup fedora*.usa
panic: nonce must be 24 bytes

goroutine 21 [running]:
lukechampine.com/us/renter.(*KeySeed).XORKeyStream(0xc0000e4020, 0xc0005e4000, 0x36600, 0x36600, 0xc0000242d0, 0x1c, 0x30, 0x0)
	/root/go/src/lukechampine.com/us/renter/meta.go:96 +0x137
lukechampine.com/us/renter.(*ShardDownloader).DownloadAndDecrypt(0xc0000e4000, 0x1, 0xc161e0, 0x64f2003c, 0x0, 0xc0001cc000, 0x0)
	/root/go/src/lukechampine.com/us/renter/download.go:148 +0x2d6
lukechampine.com/us/renter/renterutil.checkup(0xc00014e840, 0xc00008b410, 0xc0000a4a00, 0x7f361fb25550, 0xc0000961e0)
	/root/go/src/lukechampine.com/us/renter/renterutil/scan.go:85 +0x626
created by lukechampine.com/us/renter/renterutil.Checkup
	/root/go/src/lukechampine.com/us/renter/renterutil/scan.go:32 +0x89


root@sia-test:~# user checkup fedora30.tar.xz.usa
panic: nonce must be 24 bytes

goroutine 21 [running]:
lukechampine.com/us/renter.(*KeySeed).XORKeyStream(0xc0000e2020, 0xc0005da000, 0x400000, 0x400000, 0xc000024300, 0x1c, 0x30, 0x0)
	/root/go/src/lukechampine.com/us/renter/meta.go:96 +0x137
lukechampine.com/us/renter.(*ShardDownloader).DownloadAndDecrypt(0xc0000e2000, 0x0, 0xc161e0, 0x24b3b074, 0x0, 0xc0001ce000, 0x0)
	/root/go/src/lukechampine.com/us/renter/download.go:148 +0x2d6
lukechampine.com/us/renter/renterutil.checkup(0xc00014a8a0, 0xc00008b410, 0xc0000a2aa0, 0x7f7dcd48d368, 0xc0000961d0)
	/root/go/src/lukechampine.com/us/renter/renterutil/scan.go:85 +0x626
created by lukechampine.com/us/renter/renterutil.Checkup
	/root/go/src/lukechampine.com/us/renter/renterutil/scan.go:32 +0x89
root@sia-test:~# 
```
The first one I tried to do a wildcard, the second one was a straight specific filename.

Edit:  I was able to download the file and un-tar it without any errors.

**Comment by lukechampine** [comment]
Huh. Looks like when I changed the nonce handling, I forgot to update that callsite. It seems that`DownloadAndDecrypt` isn't used anywhere except `Checkup` anymore. Fixed in https://github.com/lukechampine/us/commit/c459d1f0c5c960caf300bb007e0877bce7b79411.

You can get the fix by running the following command from the `user` directory:
```
GO111MODULE=on go get lukechampine.com/us@master
```
This should update your `go.mod` to point to the latest master commit of `us`. Then run `make` as usual.
